#!/usr/bin/env bash
# update-agent-context.sh — sync AI agent context file with current stack/patterns
# Usage: bash .specify/scripts/bash/update-agent-context.sh opencode
# Mirrors spec-kit pattern; idempotent.

set -e
AGENT="${1:-opencode}"
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
DOCS="$ROOT/docs"
CONTRACTS="$ROOT/contracts"

# Determine target file
case "$AGENT" in
  opencode)
    TARGET="$ROOT/AGENTS.md"
    ALT_TARGET="$ROOT/.opencode/agent.md"
    ;;
  claude)
    TARGET="$ROOT/CLAUDE.md"
    ALT_TARGET=""
    ;;
  *)
    TARGET="$ROOT/AGENTS.md"
    ALT_TARGET=""
    ;;
esac

mkdir -p "$(dirname "$TARGET")"
if [ -n "$ALT_TARGET" ]; then mkdir -p "$(dirname "$ALT_TARGET")"; fi

# Extract versions from docs/TECH-STACK.md if exists
TECH="Next.js 14, React 18, TS 5, Tailwind 3, FastAPI 0.115 (Python 3.11), SQLAlchemy 2 async, PostgreSQL 15, LMArenaBridge, SSE, httpx, Zustand, Vercel AI SDK"
if [ -f "$DOCS/TECH-STACK.md" ]; then
  TECH="See docs/TECH-STACK.md — Next.js 14, FastAPI 0.115, PG 15, LMArenaBridge, SSE, etc."
fi

cat > "$TARGET" <<EOF
# Agent Context — AI Council

> Auto-generated by \`.specify/scripts/bash/update-agent-context.sh $AGENT\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)
> Source: research.md, data-model.md, contracts/openapi.yaml, quickstart.md

## Project
AI Council — Perplexity-style multi-model deliberation. Fan-out via asyncio.gather to 6+ models through LMArenaBridge (OpenAI-compat + session_id), fan-in via Chairman synthesis, SSE streaming, PG persistence. Free, no API keys.

## Stack (canonical Phase 1)
- **Frontend:** Next.js 14 + TypeScript 5 + Tailwind 3 + React 18 + Zustand 4 + React Hook Form 7 + Vercel AI SDK 3 (SSE)
- **Backend:** FastAPI 0.115 + Python 3.11 + Uvicorn + httpx 0.27 (async) + SQLAlchemy 2 async + Alembic 1.13 + Pydantic 2 + python-dotenv + structlog + slowapi (rate limit) + pybreaker (circuit breaker)
- **Gateway:** LMArenaBridge (latest) OpenAI-compat /v1/chat/completions + WS, tokens array, session_pool
- **DB:** PostgreSQL 15+ (asyncpg), Redis 7 optional
- **Infra:** Docker Compose (canonical local), Vercel (FE) + AWS ECS/Fargate+RDS (BE prod), GitHub Actions
- **Testing:** Pytest + pytest-asyncio + httpx MockTransport, Jest/RTL, Playwright

## Key Decisions (from research.md)
- BE→FE = SSE text/event-stream (not WS); WS only Bridge→LMArena internal. Validated R-04.
- Per-model session_id UUID per request (isolated), not pooled reuse (R-03).
- Chairman synthesis JSON {synthesis, agreements, divergences, unique_insights} with regex fallback (R-06).
- Confidence 0-1 normalized, reasoning XML <reasoning>/<answer> best-effort (R-05).
- Anon sessions allowed (user_id null), 7-day retention; auth JWT (python-jose+bcrypt), OAuth deferred Phase 2 (R-11).
- Deploy: docker-compose local Phase 1 (R-08); file upload/RAG deferred (R-10).

## Contracts (source of truth)
- OpenAPI: contracts/openapi.yaml — endpoints: GET /health, GET /models, POST /council/query (SSE), GET/DELETE /council/session/{id}, GET /council/sessions, POST /auth/register|login, GET /auth/me
- JSON Schema: contracts/council-query.json, council-session.json, model-response.json
- SSE: contracts/sse-events.md — events model_start/stream/done, critique_done, synthesis_start/stream, done, error
- Data model: data-model.md — users, council_sessions, model_responses, deliberation_log JSONB

## Rules (inferred constitution from docs/PROCESS.md + ARCHITECTURE.md)
- GitFlow (main/develop/feature/*), Conventional Commits, Squash-Merge, 1 reviewer, 80% coverage, Swagger at /docs required, env never committed.
- Secrets never to FE, CORS only FRONTEND_ORIGIN, DB private subnet, LMArena token in vault (Phase 3).
- No code before design review — research.md → data-model.md/contracts/quickstart.md must be approved before orchestrator.py.

## Quickstart
\`\`\`bash
cp .env.example .env  # fill LMARENA_TOKEN (arena-auth-prod-v1)
docker-compose up -d --build
curl http://localhost:8000/health
curl -N -X POST http://localhost:8000/council/query -H "Content-Type: application/json" -d '{"query":"hi","models":["claude","chatgpt"]}'
# FE at http://localhost:3000
\`\`\`
See quickstart.md.

## Agent Instructions
- Read docs/README.md, ARCHITECTURE.md, WORKING.md, research.md, data-model.md, contracts/openapi.yaml before editing.
- Respect phase gates: Phase 0 research only, Phase 1 design review, Phase 1 code after approval.
- Keep contracts and data-model in sync; run alembic revision --autogenerate on schema change.
- Use SSE events as per sse-events.md; validate with zod/json-schema.
- Log structured JSON with session_id/model/latency/status.

## Last Synced Artifacts
- $(ls -1 "$ROOT"/*.md 2>/dev/null | tr '\n' ' ')
- $(ls -1 "$CONTRACTS"/* 2>/dev/null | tr '\n' ' ')
EOF

if [ -n "$ALT_TARGET" ]; then cp "$TARGET" "$ALT_TARGET"; echo "Also wrote $ALT_TARGET"; fi

echo "✓ Updated $TARGET for agent: $AGENT"
echo "  Tech: $TECH"
